export const translatedCopy: Record<string, string> = {
  "Overview": "Visão geral",
  "Order history": "Histórico de pedidos",
  "Addresses": "Endereços",
  "Wishlist": "Favoritos",
  "Products": "Produtos",
  "Categories": "Categorias",
  "Orders": "Pedidos",
  "Banners": "Estandartes",
  "Analytics": "Análise",
  "Audit Log": "Registro de auditoria",
  "Users": "Usuários",
  "Remove from wishlist": "Remover dos favoritos",
  "Add to wishlist": "Adicionar aos favoritos",
  "Added to cart.": "Adicionado ao carrinho.",
  "Sorry, that's out of stock.": "Desculpe, este item está esgotado.",
  "Size": "Tamanho",
  "Variant": "Variante",
  "Save changes": "Salvar alterações",
  "Create product": "Criar produto",
  "Add banner": "Adicionar banner",
  "Add category": "Adicionar categoria",
  "Add address": "Adicionar endereço",
  "Adding…": "Adicionando…",
  "Add to Cart": "Adicionar ao carrinho",
  "item": "item",
  "items": "itens",
  "result": "resultado",
  "results": "resultados",
  "left": "restantes",
  "product": "produto",
  "(you)": "(você)",
  "of": "de",
  "for “": "para “",
  "Active": "Ativo",
  "Action": "Ação",
  "Actor": "Responsável",
  "Account created for": "Conta criada para",
  "Actor id": "ID do ator",
  "A confirmation has been recorded for order": "Uma confirmação foi registrada para o pedido",
  ". Check your email for a verification link, then": ". Verifique seu e-mail em busca de um link de verificação e, em seguida,",
  ". This page will update automatically.": ". Esta página será atualizada automaticamente.",
  "Add variant": "Adicionar variante",
  "All": "Todos",
  "All materials": "Todos os materiais",
  "Already have an account?": "Já tem uma conta?",
  "Adjust stock": "Ajustar estoque",
  "Amount": "Quantia",
  "Apartment, suite, etc. (optional)": "Apartamento, suíte, etc. (opcional)",
  "Adjust −": "Ajustar -",
  "Apply filters": "Aplicar filtros",
  "Archive": "Arquivo",
  "Approve payment": "Aprovar pagamento",
  "Archived": "Arquivado",
  "Admin Dashboard": "Painel administrativo",
  "Alt text": "Texto alternativo",
  "Audit log": "Registro de auditoria",
  "Avg. order value": "Valor médio do pedido",
  "Back to dashboard": "Voltar ao painel",
  "Back home": "Voltar ao início",
  "Cancel": "Cancelar",
  "Catalog": "Catálogo",
  "CTA label": "Etiqueta de CTA",
  "Base price (cents)": "Preço base (centavos)",
  "Back to the catalog": "Voltar ao catálogo",
  "Back to sign in": "Voltar para fazer login",
  "Category": "Categoria",
  "CTA link": "Link para CTA",
  "Change slug…": "Alterar identificador…",
  "Checked out as a guest?": "Comprou sem uma conta?",
  "Choose a category": "Escolha uma categoria",
  "Checkout": "Finalizar compra",
  "Choose a new password for your account.": "Escolha uma nova senha para sua conta.",
  "Clear": "Claro",
  "City": "Cidade",
  "Continue": "Continuar",
  "Country": "País",
  "Changing the slug can break existing links (bookmarks, shared URLs) — this won't redirect the old one.": "Alterar o slug pode quebrar links existentes (favoritos, URLs compartilhados) — isso não redirecionará o antigo.",
  "Conversion funnel — last 30 days": "Funil de conversão – últimos 30 dias",
  "Create an account": "Crie uma conta",
  "Customer": "Cliente",
  "Decline": "Declínio",
  "Delete": "Excluir",
  "Default": "Padrão",
  "Diff": "Diferença",
  "Description": "Descrição",
  "Draft": "Rascunho",
  "Don't have an account?": "Não tem uma conta?",
  "Edit": "Editar",
  "Email": "E-mail",
  "Entity": "Entidade",
  "Ends at": "Termina em",
  "Create one": "Crie um",
  "Featured": "Apresentou",
  "Filter": "Filtro",
  "Entity type": "Tipo de entidade",
  "Enter your order number and the email you used at checkout.": "Digite o número do seu pedido e o e-mail que você usou na finalização da compra.",
  "Distinct visitor sessions reaching each step, not raw event counts.": "Sessões de visitantes distintas atingindo cada etapa, e não contagens brutas de eventos.",
  "Forgot password?": "Esqueceu sua senha?",
  "Forgot password": "Esqueceu sua senha",
  "Full name": "Nome completo",
  "Hero": "Destaque",
  "If that email has an account, a reset link is on its way.": "Se esse e-mail tiver uma conta, um link de redefinição estará a caminho.",
  "Image URL": "URL da imagem",
  "Images": "Imagens",
  "In stock": "Em estoque",
  "In stock only": "Somente em estoque",
  "Find my order": "Encontre meu pedido",
  "Find your order": "Encontre seu pedido",
  "Image file": "Arquivo de imagem",
  "Lost in the wilds": "Perdido na selva",
  "Joined": "Cadastro em",
  "Material": "Material",
  "Max": "Máx.",
  "Long description": "Descrição longa",
  "Manage your saved shipping addresses.": "Gerencie seus endereços de entrega salvos.",
  "Min": "Mínimo",
  "Mark fulfilled": "Marca cumprida",
  "Low stock": "Estoque baixo",
  "Name": "Nome",
  "Medivi Shop is a fictional portfolio project. This page is a placeholder — no real terms of service apply, since no real transactions take place here.": "Medivi Shop é um projeto de portfólio fictício. Esta página é um espaço reservado – nenhum termo de serviço real se aplica, já que nenhuma transação real ocorre aqui.",
  "Medivi Shop is a fictional portfolio project. This page is a placeholder — no real data-collection policy applies, since no real personal data is processed here.": "Medivi Shop é um projeto de portfólio fictício. Esta página é um espaço reservado — nenhuma política real de coleta de dados se aplica, uma vez que nenhum dado pessoal real é processado aqui.",
  "Medivi Shop is a fictional portfolio project. This page is a placeholder — no real shipping or returns policy applies, since no physical goods are ever shipped.": "Medivi Shop é um projeto de portfólio fictício. Esta página é um espaço reservado – nenhuma política real de envio ou devolução se aplica, uma vez que nenhum produto físico é enviado.",
  "New password": "Nova Senha",
  "New product": "Novo produto",
  "Next": "Próxima",
  "No sales yet.": "Nenhuma venda ainda.",
  "No paid orders in this window yet.": "Ainda não há pedidos pagos nesta janela.",
  "Only": "Apenas",
  "Mock payment processor": "Processador de pagamento simulado",
  "No real payment provider is configured — this stands in for a Stripe-hosted checkout page.": "Nenhum provedor de pagamento real está configurado – isso representa uma página de checkout hospedada pelo Stripe.",
  "No visits recorded in this window yet.": "Nenhuma visita registrada nesta janela ainda.",
  "Order": "Pedido",
  "Order number": "Número do pedido",
  "None (top-level)": "Nenhum (nível superior)",
  "Order summary": "Resumo do pedido",
  "Nothing running low.": "Nada está acabando.",
  "Page": "Página",
  "Out of stock": "Fora de estoque",
  "Payment failed": "Falha no pagamento",
  "Password": "Senha",
  "Placed": "Colocado",
  "Previous": "Anterior",
  "Placement": "Colocação",
  "Postal code": "CEP",
  "Price": "Preço",
  "Privacy Policy": "política de Privacidade",
  "Payment processing": "Processando pagamento",
  "Product": "Produto",
  "Price override (cents)": "Substituição de preço (centavos)",
  "Price override": "Substituição de preço",
  "Price range": "Faixa de preço",
  "Parent category": "Categoria pai",
  "Proceed to checkout": "Fazer o check-out",
  "Refund": "Reembolso",
  "Reset password": "Redefinir senha",
  "Recent orders": "Pedidos recentes",
  "Relevance": "Relevância",
  "Remove": "Remover",
  "Revenue": "Receita",
  "Restore": "Restaurar",
  "Role": "Papel",
  "SKU": "SKU",
  "SEO title": "Título SEO",
  "Search": "Buscar",
  "Set as default": "Definir como padrão",
  "SEO description": "Descrição SEO",
  "Revenue — last 30 days": "Receita – últimos 30 dias",
  "Restock +": "Reabastecer +",
  "Shipping & Returns": "Envios e Devoluções",
  "Shipping address": "Endereço para envio",
  "Shipping": "Frete",
  "Shop by category": "Comprar por categoria",
  "Shipping method": "Método de envio",
  "Short description": "Breve descrição",
  "Sign in": "Entrar",
  "Signed in as": "Conectado como",
  "Something went wrong": "Algo deu errado",
  "Sort": "Ordenar",
  "Sort by": "Ordenar por",
  "Sort order": "Ordem de classificação",
  "Shipping to": "Envio para",
  "Starts at": "Começa às",
  "Status": "Status",
  "Slug": "Lesma",
  "State / region": "Estado/região",
  "Street address": "endereço da Rua",
  "Stock": "Estoque",
  "Subscribe": "Inscrever-se",
  "Subtitle": "Legenda",
  "Subtotal": "Subtotal",
  "Terms of Service": "Termos de Serviço",
  "Thank you for your order!": "Obrigado pelo seu pedido!",
  "Title": "Título",
  "This order has already been processed.": "Este pedido já foi processado.",
  "Thanks — you're on the list.": "Obrigado - você está na lista.",
  "This page doesn't exist — the road ends here. Head back to the catalog to keep browsing.": "Esta página não existe – o caminho termina aqui. Volte ao catálogo para continuar navegando.",
  "Total": "Total",
  "Track and review your past orders.": "Acompanhe e revise seus pedidos anteriores.",
  "This reset link is missing or invalid. Request a new one from the forgot-password page.": "Este link de redefinição está ausente ou é inválido. Solicite uma nova na página de esquecimento da senha.",
  "Try again": "Tente novamente",
  "Units": "Unidades",
  "Variants": "Variantes",
  "Top products": "Principais produtos",
  "We hit a snag loading this page. Give it another try, or head back to the shop.": "Encontramos um obstáculo ao carregar esta página. Tente novamente ou volte para a loja.",
  "Verify your email before signing in — check your inbox for the link.": "Verifique seu e-mail antes de fazer login – verifique o link em sua caixa de entrada.",
  "This admin page failed to load. Give it another try, or head back to the dashboard.": "Esta página de administração falhou ao carregar. Tente novamente ou volte para o painel.",
  "Track orders, save addresses, and build a wishlist.": "Rastreie pedidos, salve endereços e crie uma lista de desejos.",
  "Welcome,": "Bem-vindo,",
  "We hit a snag loading your account. Give it another try, or head back to the shop.": "Encontramos um problema ao carregar sua conta. Tente novamente ou volte para a loja.",
  "When": "Quando",
  "We're confirming payment for order": "Estamos confirmando o pagamento do pedido",
  "We'll email you a link to reset it.": "Enviaremos um e-mail para você com um link para redefini-lo.",
  "Welcome back, adventurer.": "Boas-vindas de volta, aventureiro.",
  "You might also like": "Você também pode gostar",
  "We couldn't find an order matching that number and email.": "Não foi possível encontrar um pedido que corresponda a esse número e e-mail.",
  "sign in": "entrar",
  "Your Cart": "Seu carrinho",
  "Your Wishlist": "Seus favoritos",
  "Yes, unlock it": "Sim, desbloqueie",
  "was not charged. Your cart is unchanged — you can try again.": "não foi cobrado. Seu carrinho permanece inalterado. Você pode tentar novamente.",
  "Standard": "Padrão",
  "Mithril Chestplate": "Peitoral de mithril",
  "Velvet": "Veludo",
  "Potions": "Poções",
  "Silver": "Prata",
  "Shard of the Frostfall Blade": "Fragmento da Lâmina Frostfall",
  "A brief but noticeable spring in your step — favored by couriers and thieves.": "Um movimento breve, mas perceptível, no seu passo – favorecido por mensageiros e ladrões.",
  "Mithril": "Mithril",
  "Broad-spectrum, bitter, and worth carrying two of.": "Amplo espectro, amargo e vale a pena carregar dois deles.",
  "Dragonscale Helm": "Elmo de Escama de Dragão",
  "Steel": "Aço",
  "The backbone of a knight's kit — rigid, heavy, and hard to get past.": "A espinha dorsal do kit de um cavaleiro — rígido, pesado e difícil de superar.",
  "Steel Great Helm": "Grande Elmo de Aço",
  "Dragonbone Greatsword": "Espadão de osso de dragão",
  "Steel Plate Cuirass": "Couraça em Chapa de Aço",
  "Trimmed in gold thread, worn by those with a court to attend rather than a battle.": "Enfeitado com fio de ouro, usado por aqueles que têm uma corte para assistir, em vez de uma batalha.",
  "Cloaks": "Capas",
  "Gold & Ember": "Ouro e Brasa",
  "Woven with something that isn't quite thread — it drinks torchlight rather than reflecting it.": "Tecido com algo que não é exatamente um fio – absorve a luz da tocha em vez de refleti-la.",
  "Plate-grade protection at a fraction of the weight — and the price to match.": "Proteção de nível de placa por uma fração do peso – e o preço correspondente.",
  "Herbal Tincture": "Tintura de ervas",
  "Alchemical Brew": "Cerveja Alquímica",
  "Full-face coverage for the tournament yard or the front line.": "Cobertura facial completa para o pátio do torneio ou para a linha de frente.",
  "Overlapping scale plates that shrug off flame better than steel ever could.": "Placas de escala sobrepostas que evitam as chamas melhor do que o aço jamais conseguiria.",
  "A dull grey stone on a plain chain — until it flares white at the first sign of danger.": "Uma pedra cinza opaca em uma corrente simples – até ficar branca ao primeiro sinal de perigo.",
  "Warded Stone": "Pedra Protegida",
  "Idol of the Sunken Temple": "Ídolo do Templo Submerso",
  "Closes shallow cuts and eases bruising within minutes.": "Fecha cortes superficiais e alivia hematomas em minutos.",
  "Steel Broadsword": "Espada larga de aço",
  "Oak & Iron": "Carvalho e Ferro",
  "Heavier than a longsword, built to cleave through mail and morale alike.": "Mais pesada que uma espada longa, construída para destruir tanto a cota de malha quanto o moral.",
  "A dependable double-edged blade, favored by militia and mercenaries alike.": "Uma lâmina confiável de dois gumes, preferida tanto por milicianos quanto por mercenários.",
  "Faintly warm to the touch, always. No one has explained why.": "Levemente quente ao toque, sempre. Ninguém explicou o porquê.",
  "Thousands of interlocked rings, heavy but forgiving in a scrap.": "Milhares de anéis entrelaçados, pesados, mas indulgentes em uma briga.",
  "Small, light, and easy to strap on — a first shield for a first adventure.": "Pequeno, leve e fácil de colocar – um primeiro escudo para uma primeira aventura.",
  "Carved from a fallen wyrm's rib, lighter than its size suggests and slow to dull.": "Esculpida na costela de um ancião caído, mais leve do que seu tamanho sugere e lenta a cega.",
  "Twin Fang Daggers": "Adagas Presas Gêmeas",
  "Flexible and quiet — the choice of scouts and cutpurses in equal measure.": "Flexível e silencioso – a escolha de batedores e batedores em igual medida.",
  "Meant to be seen from the far side of a battlefield — and it is.": "Feito para ser visto do outro lado do campo de batalha – e é.",
  "Swords": "Espadas",
  "Shields": "Escudos",
  "Dragonbone": "Osso de Dragão",
  "Relics": "Relíquias",
  "Leather Cap": "Boné de couro",
  "Leather": "Couro",
  "Full-body coverage on foot or horseback, standard issue for guild guards.": "Cobertura de corpo inteiro a pé ou a cavalo, padrão para guardas de guilda.",
  "Carried through a real campaign and it shows — sold as-is, scars included.": "Realizei uma campanha real e ela fica evidente - vendida no estado em que se encontra, com cicatrizes incluídas.",
  "A matched pair, balanced for throwing or close-quarters work.": "Um par combinado, equilibrado para arremesso ou trabalho corpo a corpo.",
  "Shadowweave Cloak": "Capa de trama sombria",
  "Traveler's Cloak": "Manto do Viajante",
  "Greater Healing Potion": "Poção de cura maior",
  "Enchanted Ice": "Gelo Encantado",
  "Wool": "Lã",
  "Armor": "Armadura",
  "Steel Tower Shield": "Escudo da Torre de Aço",
  "Chestplates": "Peitorais",
  "An open-faced helm balancing protection with a clear line of sight.": "Uma proteção de equilíbrio de leme aberto com uma linha de visão clara.",
  "Fitted scale plate that turns aside blade and flame alike.": "Placa de escala equipada que desvia a lâmina e a chama.",
  "Featherlight and quick to answer, prized by scouts who travel far and fast.": "Leve como uma pena e de resposta rápida, apreciado por batedores que viajam para longe e rápido.",
  "Embroidered in real silver thread — heavier, and pricier, than it looks.": "Bordado com fio de prata verdadeiro – mais pesado e mais caro do que parece.",
  "Weathered Canvas": "Tela resistida",
  "Dragonscale Shield": "Escudo de Escama de Dragão",
  "Iron Longsword": "Espada longa de ferro",
  "Dragonscale": "Escama de dragão",
  "Coral & Bronze": "Coral e Bronze",
  "A duelist's blade — fast, precise, and unusually effective against the unnatural.": "A lâmina de um duelista — rápida, precisa e extraordinariamente eficaz contra o que não é natural.",
  "Iron Helm": "Elmo de Ferro",
  "All that remains of a legendary sword — still cold enough to frost a gauntlet.": "Tudo o que resta de uma espada lendária – ainda fria o suficiente para congelar uma manopla.",
  "Iron Kite Shield": "Escudo de pipa de ferro",
  "Silver Rapier": "Florete Prateado",
  "Ten minutes of strength you did not have ten minutes ago.": "Dez minutos de força que você não tinha há dez minutos.",
  "Size: L": "Tamanho: G",
  "Chainmail Hauberk": "Cota de malha",
  "Oiled wool that sheds rain and road-dust in equal measure.": "Lã oleada que elimina chuva e poeira da estrada em igual medida.",
  "Size: S": "Tamanho: P",
  "Antidote Vial": "Frasco de antídoto",
  "Size: XL": "Tamanho: GG",
  "Size: M": "Tamanho: M",
  "Bound in iron at the rim, favored by skirmishers who need to move.": "Encadernado em ferro na borda, preferido por escaramuçadores que precisam se mover.",
  "Amulet of Warding": "Amuleto de Proteção",
  "Iron": "Ferro",
  "Mends deep wounds fast enough to get you back on your feet mid-brawl.": "Cura feridas profundas com rapidez suficiente para que você se recupere no meio da briga.",
  "Guild Standard Banner": "Estandarte Padrão da Guilda",
  "Crimson War Banner": "Bandeira da Guerra Carmesim",
  "Helmets": "Elmos",
  "Minor Healing Potion": "Poção de Cura Menor",
  "Tattered Field Banner": "Banner de campo esfarrapado",
  "Dyed Wool": "Lã Tingida",
  "Royal Velvet Cloak": "Manto Real de Veludo",
  "Oak": "Carvalho",
  "Elixir of Swift Feet": "Elixir dos Pés Rápidos",
  "Ranger's Hooded Cloak": "Capa com Capuz do Ranger",
  "Boiled leather, stitched snug — better than nothing, worse than a helm.": "Couro fervido, bem costurado – melhor que nada, pior que um elmo.",
  "Plain, sturdy, and easy to spot across a crowded market square.": "Simples, robusto e fácil de localizar em uma praça de mercado lotada.",
  "Leather Jerkin": "Jerkin de couro",
  "Ring of the Ember King": "Anel do Rei Brasa",
  "Canvas": "Tela",
  "Mithril Shortsword": "Espada Curta de Mithril",
  "Shadowweave": "Trama de sombra",
  "Oakheart Round Shield": "Escudo redondo de carvalho",
  "Potion of Giant Strength": "Poção de Força Gigante",
  "Emblem of the Silver Watch": "Emblema do Relógio de Prata",
  "Wool & Leather": "Lã e Couro",
  "Wooden Buckler": "Broquel de madeira",
  "Heavy enough to brace a siege line, awkward everywhere else.": "Pesado o suficiente para proteger uma linha de cerco, estranho em qualquer outro lugar.",
  "Recovered from beneath the tideline — the carvings shift if you look away and back.": "Recuperado abaixo da linha da maré - as esculturas mudam se você olhar para longe e para trás.",
  "Silk & Silver Thread": "Fio de seda e prata",
  "Mottled green and brown, cut to blend into the treeline.": "Manchado de verde e marrom, cortado para combinar com a linha das árvores.",
  "Sign out": "Sair",
  "Email address": "Endereço de email",
  "Qty": "Quantidade",
  "image gallery": "galeria de imagens",
  "Footer": "Rodapé",
  "Next promotion": "Próxima promoção",
  "user id…": "ID do usuário…",
  "Your past orders will show up here.": "Seus pedidos anteriores aparecerão aqui.",
  "Previous promotion": "Promoção anterior",
  "No addresses yet": "Ainda não há endereços",
  "Your cart is empty": "Seu carrinho está vazio",
  "Add something from the catalog before checking out.": "Adicione algo do catálogo antes de finalizar a compra.",
  "Add your first banner to feature it on the landing page.": "Adicione seu primeiro banner para apresentá-lo na página de destino.",
  "Decrease quantity": "Diminuir quantidade",
  "Search by email…": "Pesquisar por e-mail…",
  "Promotions": "Promoções",
  "Try a different email search.": "Tente uma pesquisa de e-mail diferente.",
  "Add an address to speed up checkout next time.": "Adicione um endereço para agilizar a finalização da compra na próxima vez.",
  "No banners yet": "Ainda não há banners",
  "No categories yet": "Nenhuma categoria ainda",
  "Save products you're eyeing by tapping the heart on any item.": "Salve os produtos que você está procurando tocando no coração de qualquer item.",
  "Admin navigation": "Navegação administrativa",
  "No orders yet": "Ainda não há pedidos",
  "Browse categories": "Navegar por categorias",
  "Your wishlist is empty": "Sua lista de desejos está vazia",
  "Increase quantity": "Aumentar quantidade",
  "Product images": "Imagens do produto",
  "Add your first category to get started.": "Adicione sua primeira categoria para começar.",
  "Optional": "Opcional",
  "Add something from the catalog to get started.": "Adicione algo do catálogo para começar.",
  "Try a different actor id or entity type.": "Experimente um ID de ator ou tipo de entidade diferente.",
  "Defaults to the product name": "O padrão é o nome do produto",
  "Product name…": "Nome do produto…",
  "Pagination": "Paginação",
  "Breadcrumb": "Pão ralado",
  "No products match": "Nenhum produto corresponde",
  "Any": "Qualquer",
  "No users match": "Nenhum usuário corresponde",
  "Account navigation": "Navegação da conta",
  "Try a different search term or clear the filters.": "Experimente um termo de pesquisa diferente ou limpe os filtros.",
  "Featured promotions": "Promoções em destaque",
  "No matching audit entries": "Nenhuma entrada de auditoria correspondente",
  "Try a different status filter.": "Experimente um filtro de status diferente.",
  "No orders match": "Nenhum pedido corresponde"
};
