"use client";
import Link from "next/link";
import { products } from "@/lib/catalog";
import { COPY, DEPTS, GOODS, localizedDept } from "@/lib/armory";
import { useDemo } from "@/components/demo-provider";
import { useArmory, Mark, ProductFrame } from "@/components/armory-primitives";
import { ProductCard } from "@/components/product-card";
export default function Home() {
  const { a, locale, formatMoney, tr } = useArmory();
  const { state } = useDemo();
  const featured = GOODS.slice(0,5).flatMap(good => { const product = products.find(item => item.slug === good.slug); return product && !state.hiddenProducts.includes(product.slug) ? [product] : []; });
  const hero = products[0]!;
  const words = COPY[locale === "en" ? "en" : "pt"].merchantWord;
  return <>
    <section className="arm-hero overflow-hidden"><div className="arm-wrap grid min-h-[660px] items-center gap-10 py-[78px] min-[1200px]:grid-cols-[1.04fr_.96fr]">
      <div className="max-[1199px]:order-2"><h1 className="arm-display text-[60px] leading-[.86] tracking-[.02em] text-[#efe6cc] sm:text-[92px]">Medivi</h1><div className="arm-ui mt-5 flex items-center gap-3 text-[15px] uppercase tracking-[.2em] text-[#c9a257]"><span className="arm-rule w-14"/><Mark name="anvil" tone="bronze" size={20}/>{a("house")}</div><p className="arm-ui mt-9 max-w-[19ch] text-[32px] font-light leading-[1.16] text-[#e9dfc4] sm:text-[38px]">{a("heroLine1")}<br/><em className="text-[#cbb98f]">{a("heroLine2")}</em></p><div className="mt-10 flex flex-wrap items-center gap-6"><Link href="/catalog" className="arm-button">{a("enterArmory")} →</Link><Link href="#floor" className="arm-link">{a("seeTheWares")} →</Link></div><div className="arm-ui mt-14 flex flex-wrap gap-x-4 gap-y-2 text-[14px] text-[#9a8b6a]"><span>{a("guildLine")}</span><span>◆</span><span>{a("estLine")}</span><span>◆</span><span>{a("placeLine")}</span></div></div>
      <div className="arm-hero-product relative mx-auto w-full max-w-[480px] max-[1199px]:order-1" data-reveal="mask"><ProductFrame src={hero.image} alt={tr(hero.name)} priority className="aspect-square"/><div className="arm-hero-caption arm-ui"><strong className="block text-[19px]">{tr(hero.name)}</strong><span className="mt-1 block text-[15px] text-[#cbb98f]">{formatMoney(hero.priceCents)}</span></div></div>
    </div></section>
    <section className="border-y border-[#0a0908] bg-[linear-gradient(#32251a,#241a12)]"><div className="arm-wrap grid gap-7 py-6 md:grid-cols-3">{words.map((word,i)=><div key={word.title} className="flex gap-4"><Mark name={["seal","anvil","scroll"][i]!} tone="bronze" size={26}/><div><h2 className="arm-ui text-[18px]">{word.title}</h2><p className="mt-1 text-[14px] leading-6 text-[#b7a67d]">{word.text}</p></div></div>)}</div></section>
    <section id="departments" className="arm-wrap scroll-mt-24 pt-[86px] pb-10"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="arm-eyebrow">{a("departmentsEyebrow")}</p><h2 className="arm-title mt-2 text-[46px]">{a("departmentsHead")}</h2></div><p className="max-w-[34ch] italic leading-7 text-[#b7a67d]">{a("departmentsNote")}</p></div><div className="mt-9 grid gap-[18px] min-[900px]:grid-cols-2 min-[1200px]:grid-cols-3">{DEPTS.map(dept=><Link key={dept.slug} href={`/catalog?dept=${dept.slug}`} className="arm-plate flex gap-4 p-5 hover:bg-[#2e2318]"><Mark name={dept.mark} size={34}/><div><h3 className="arm-ui text-[24px] leading-tight text-[#efe6cc]">{localizedDept(locale,dept.slug)?.name}</h3><p className="mt-1 text-[14px] leading-6 text-[#b7a67d]">{localizedDept(locale,dept.slug)?.description}</p><span className="arm-ui mt-2 block text-[13px] uppercase text-[#9a8b6a]">{products.filter(product=>!state.hiddenProducts.includes(product.slug) && (dept.slug==="armory" ? product.category==="swords" : dept.slug==="bulwark" ? ["armor","shields"].includes(product.category) : dept.slug==="wayfarer" ? product.category==="cloaks" : dept.slug==="alchemist" ? product.category==="potions" : product.category==="relics")).length} {a("wares")}</span></div></Link>)}</div></section>
    <section id="floor" className="arm-wrap scroll-mt-24 pt-[60px] pb-5"><div className="mb-9 flex items-center gap-5"><h2 className="arm-title whitespace-nowrap text-[42px]">{a("floorHead")}</h2><span className="arm-rule flex-1" data-reveal="rule"/><Mark name="knot" tone="bronze" size={22}/></div><div className="arm-floor">{featured.map((product,i)=><ProductCard key={product.slug} product={product} tall={i<2}/>)}</div></section>
    <section className="arm-wrap py-[80px]"><div className="arm-parchment relative mx-auto max-w-[760px] rotate-[-.45deg] px-8 py-9 sm:px-10"><Mark name="scroll" tone="ink" size={34}/><h2 className="arm-ui mt-3 text-[26px]">{a("noticeHead")}</h2><p className="mt-3 text-[15px] leading-7 text-[#4a3a24]">{a("noticeText")}</p><p className="mt-4 text-[14px] italic text-[#6a5638]">{a("noticeSigned")}</p></div></section>
  </>;
}
