export const GOODS = [
  { slug:"dragonbone-greatsword", dept:"armory", priceCents:32000, stock:4, rar:4,
    en:{ name:"Dragonbone Greatsword", material:"Dragonbone", origin:"The Hollow, beyond Vael", era:"Age of Ash", weight:"9 stone", maker:"Odran Blackhand", makerNote:"Ironmark Guild, third seal",
      description:"Carved from a fallen wyrm's rib, lighter than its size suggests and slow to dull.",
      note:"Three returned from the Hollow carrying these. Only one still spoke, and he would not say what he had seen." },
    pt:{ name:"Espadão de Osso de Dragão", material:"Osso de dragão", origin:"O Vazio, além de Vael", era:"Era das Cinzas", weight:"9 arrobas", maker:"Odran Mão-Negra", makerNote:"Guilda de Ironmark, terceiro selo",
      description:"Esculpido na costela de um dragão caído, mais leve do que parece e difícil de perder o fio.",
      note:"Três voltaram do Vazio carregando estes. Só um ainda falava, e não dizia o que tinha visto." } },
  { slug:"shard-of-the-frostfall-blade", dept:"relics", priceCents:45000, stock:3, rar:5,
    en:{ name:"Shard of the Frostfall Blade", material:"Enchanted Ice", origin:"Northern Marches", era:"Before the Long Winter", weight:"2 stone", maker:"Unknown hand", makerNote:"No guild claims it",
      description:"All that remains of a legendary sword — still cold enough to frost a gauntlet.",
      note:"It has not melted in eleven years under my roof. I keep it in the cold room regardless." },
    pt:{ name:"Fragmento da Lâmina Glacial", material:"Gelo encantado", origin:"Marcas do Norte", era:"Antes do Longo Inverno", weight:"2 arrobas", maker:"Mão desconhecida", makerNote:"Nenhuma guilda o reivindica",
      description:"O que resta de uma espada lendária, ainda fria o bastante para congelar uma manopla.",
      note:"Não derreteu em onze anos sob meu teto. Ainda assim, guardo-o na câmara fria." } },
  { slug:"mithril-chestplate", dept:"bulwark", priceCents:52000, stock:8, rar:4,
    en:{ name:"Mithril Chestplate", material:"Mithril", origin:"Ironmark", era:"Third Age of Aster", weight:"4 stone", maker:"Maera of Greyfen", makerNote:"Master of the plate benches",
      description:"Plate-grade protection at a fraction of the weight — and the price to match.",
      note:"Maera will not sell two in the same season. This is the season's." },
    pt:{ name:"Peitoral de Mithril", material:"Mithril", origin:"Ironmark", era:"Terceira Era de Aster", weight:"4 arrobas", maker:"Maera de Greyfen", makerNote:"Mestra das bancadas de armadura",
      description:"Proteção de armadura pesada com uma fração do peso e um preço à altura.",
      note:"Maera não vende dois na mesma estação. Este é o desta." } },
  { slug:"dragonscale-shield", dept:"bulwark", priceCents:41000, stock:5, rar:4,
    en:{ name:"Dragonscale Shield", material:"Dragonscale", origin:"Ashfell", era:"Age of Embers", weight:"7 stone", maker:"Hadrik Ost", makerNote:"Scale-binder of Ashfell",
      description:"Overlapping scale plates that shrug off flame better than steel ever could.",
      note:"Held against forge-fire for a count of forty. The hand behind it stayed cool." },
    pt:{ name:"Escudo de Escamas de Dragão", material:"Escamas de dragão", origin:"Ashfell", era:"Era das Brasas", weight:"7 arrobas", maker:"Hadrik Ost", makerNote:"Encaixador de escamas de Ashfell",
      description:"Placas de escamas sobrepostas que resistem às chamas melhor do que o aço.",
      note:"Mantido contra o fogo da forja por quarenta contagens. A mão atrás dele ficou fria." } },
  { slug:"shadowweave-cloak", dept:"wayfarer", priceCents:26000, stock:7, rar:3,
    en:{ name:"Shadowweave Cloak", material:"Shadowweave", origin:"Greyfen looms", era:"Third Age of Aster", weight:"half a stone", maker:"Sister Ilveth", makerNote:"Of the Grey Hand",
      description:"Woven with something that drinks torchlight rather than reflecting it.",
      note:"Do not ask what the thread is. Ilveth answers that question only once per customer." },
    pt:{ name:"Capa de Trama Sombria", material:"Trama sombria", origin:"Teares de Greyfen", era:"Terceira Era de Aster", weight:"meia arroba", maker:"Irmã Ilveth", makerNote:"Da Mão Cinzenta",
      description:"Tecida com um material que absorve a luz das tochas em vez de refleti-la.",
      note:"Não pergunte de que é o fio. Ilveth responde isso uma vez por cliente." } },
  { slug:"amulet-of-warding", dept:"relics", priceCents:21000, stock:9, rar:3,
    en:{ name:"Amulet of Warding", material:"Warded Stone", origin:"Sunken Coast", era:"Age of Chains", weight:"a few ounces", maker:"Brother Anselm", makerNote:"Ward-cutter, Order of the Grey Hand",
      description:"A dull grey stone on a plain chain — until it flares white at danger.",
      note:"Flared twice on the road here. Both times before the dogs noticed anything." },
    pt:{ name:"Amuleto de Proteção", material:"Pedra protegida", origin:"Costa Submersa", era:"Era das Correntes", weight:"algumas onças", maker:"Irmão Anselm", makerNote:"Talhador de proteções, Ordem da Mão Cinzenta",
      description:"Uma pedra cinza numa corrente simples que brilha em branco diante do perigo.",
      note:"Brilhou duas vezes na estrada até aqui. Nas duas, antes dos cães perceberem algo." } },
  { slug:"silver-rapier", dept:"armory", priceCents:11000, stock:15, rar:3,
    en:{ name:"Silver Rapier", material:"Silver", origin:"Low Quarter of Vael", era:"Third Age of Aster", weight:"2 stone", maker:"Torvald Quen", makerNote:"Duelling smith, two seals",
      description:"A duelist's blade — fast, precise, and unusually effective against the unnatural.",
      note:"Quen files the edge thin. Bring it back to him, not to me." },
    pt:{ name:"Florete de Prata", material:"Prata", origin:"Bairro Baixo de Vael", era:"Terceira Era de Aster", weight:"2 arrobas", maker:"Torvald Quen", makerNote:"Ferreiro de duelo, dois selos",
      description:"Uma lâmina de duelista: rápida, precisa e especialmente eficaz contra o sobrenatural.",
      note:"Quen deixa o fio fino. Leve-o de volta a ele, não a mim." } },
  { slug:"steel-great-helm", dept:"bulwark", priceCents:6800, stock:18, rar:2,
    en:{ name:"Steel Great Helm", material:"Steel", origin:"Ironmark", era:"Third Age of Aster", weight:"3 stone", maker:"Ironmark benches", makerNote:"Guild-marked, common run",
      description:"Full-face coverage for the tournament yard or the front line.",
      note:"Sized to four heads. Try them in the yard before you ride." },
    pt:{ name:"Elmo Pesado de Aço", material:"Aço", origin:"Ironmark", era:"Terceira Era de Aster", weight:"3 arrobas", maker:"Bancadas de Ironmark", makerNote:"Marca da guilda, série comum",
      description:"Proteção completa para o rosto, ideal para torneios ou a linha de frente.",
      note:"Vem em quatro tamanhos. Experimente no pátio antes de partir." } },
  { slug:"iron-longsword", dept:"armory", priceCents:4500, stock:40, rar:1,
    en:{ name:"Iron Longsword", material:"Iron", origin:"Ironmark", era:"Third Age of Aster", weight:"3 stone", maker:"Ironmark benches", makerNote:"Common run, guild-marked",
      description:"A dependable double-edged blade, favored by militia and mercenaries alike.",
      note:"Forty in the rack. Nobody has returned one yet." },
    pt:{ name:"Espada Longa de Ferro", material:"Ferro", origin:"Ironmark", era:"Terceira Era de Aster", weight:"3 arrobas", maker:"Bancadas de Ironmark", makerNote:"Série comum, marca da guilda",
      description:"Uma lâmina confiável de dois gumes, apreciada por milícias e mercenários.",
      note:"Quarenta no suporte. Ninguém devolveu nenhuma ainda." } },
  { slug:"oakheart-round-shield", dept:"bulwark", priceCents:4200, stock:22, rar:1,
    en:{ name:"Oakheart Round Shield", material:"Oak & Iron", origin:"Vale of Caerwyn", era:"Third Age of Aster", weight:"4 stone", maker:"Wren Calloway", makerNote:"Shieldwright of Caerwyn",
      description:"Bound in iron at the rim, favored by skirmishers who need to move.",
      note:"Light enough to run with. Wren rims them herself." },
    pt:{ name:"Escudo Redondo de Carvalho", material:"Carvalho e ferro", origin:"Vale de Caerwyn", era:"Terceira Era de Aster", weight:"4 arrobas", maker:"Wren Calloway", makerNote:"Escudeira de Caerwyn",
      description:"Reforçado com ferro na borda, preferido por combatentes que precisam de mobilidade.",
      note:"Leve o bastante para correr. Wren faz as bordas ela mesma." } },
  { slug:"travelers-cloak", dept:"wayfarer", priceCents:2200, stock:30, rar:1,
    en:{ name:"Traveler's Cloak", material:"Wool", origin:"Greyfen looms", era:"Third Age of Aster", weight:"half a stone", maker:"Greyfen weavers", makerNote:"Oiled by the bolt",
      description:"Oiled wool that sheds rain and road-dust in equal measure.",
      note:"The cheapest thing in the shop that will actually keep you alive." },
    pt:{ name:"Capa de Viajante", material:"Lã", origin:"Teares de Greyfen", era:"Terceira Era de Aster", weight:"meia arroba", maker:"Tecelãs de Greyfen", makerNote:"Enceradas por rolo",
      description:"Lã encerada que repele tanto a chuva quanto a poeira da estrada.",
      note:"A coisa mais barata da loja que de fato mantém você vivo." } },
  { slug:"greater-healing-potion", dept:"alchemist", priceCents:2600, stock:60, rar:2,
    en:{ name:"Greater Healing Potion", material:"Herbal Tincture", origin:"Ashfell Apothecary", era:"Brewed this season", weight:"a flask", maker:"The Ashfell coven", makerNote:"Sealed with green wax",
      description:"Mends deep wounds fast enough to get you back on your feet mid-brawl.",
      note:"Drink it standing. Those who drink it lying down tend to stay there." },
    pt:{ name:"Poção de Cura Maior", material:"Tintura de ervas", origin:"Boticário de Ashfell", era:"Preparada nesta estação", weight:"um frasco", maker:"O coven de Ashfell", makerNote:"Selada com cera verde",
      description:"Cura ferimentos profundos a tempo de você voltar à luta.",
      note:"Beba de pé. Quem bebe deitado costuma continuar deitado." } },
  { slug:"potion-of-giant-strength", dept:"alchemist", priceCents:3200, stock:30, rar:2,
    en:{ name:"Potion of Giant Strength", material:"Alchemical Brew", origin:"Ashfell Apothecary", era:"Brewed this season", weight:"a flask", maker:"The Ashfell coven", makerNote:"Sealed with red wax",
      description:"Ten minutes of strength you did not have ten minutes ago.",
      note:"Ten minutes, no more. Count them, and be somewhere safe when you finish." },
    pt:{ name:"Poção de Força Gigante", material:"Preparado alquímico", origin:"Boticário de Ashfell", era:"Preparada nesta estação", weight:"um frasco", maker:"O coven de Ashfell", makerNote:"Selada com cera vermelha",
      description:"Dez minutos de uma força que você não tinha dez minutos atrás.",
      note:"Dez minutos, não mais. Conte-os e esteja em lugar seguro ao terminar." } },
];

export const DEPTS = [
  { slug:"armory", mark:"broadsword", en:{ name:"The Armory", description:"Blades and edged work, from militia iron to the rare." },
    pt:{ name:"O Arsenal", description:"Lâminas e trabalho de fio, do ferro de milícia ao raro." } },
  { slug:"bulwark", mark:"shield", en:{ name:"The Bulwark", description:"Shields, plate and helms. What stands between you and the swing." },
    pt:{ name:"O Baluarte", description:"Escudos, armaduras e elmos. O que fica entre você e o golpe." } },
  { slug:"wayfarer", mark:"cloak", en:{ name:"Wayfarer Goods", description:"Cloaks and road cloth for weather, dust and long distance." },
    pt:{ name:"Bens de Viajante", description:"Capas e tecidos de estrada para clima, poeira e longas distâncias." } },
  { slug:"relics", mark:"rune", en:{ name:"Relics", description:"Objects of uncertain origin. Sold as found, priced as rare." },
    pt:{ name:"Relíquias", description:"Objetos de origem incerta. Vendidos como achados, cobrados como raros." } },
  { slug:"alchemist", mark:"potion", en:{ name:"Alchemist's Shelf", description:"Tinctures and brews from the Ashfell benches, sealed in wax." },
    pt:{ name:"Prateleira do Alquimista", description:"Tinturas e preparados das bancadas de Ashfell, selados em cera." } },
];

export const RARITY = {
  en: ["", "Common ware", "Guild-marked", "Rare", "Relic", "Legend"],
  pt: ["", "Artigo comum", "Marca da guilda", "Raro", "Relíquia", "Lenda"],
};

export const COPY = {
  en: {
    banner: "A portfolio demonstration. No coin changes hands, no order is ever sent.",
    house: "Armorer & Provisioner",
    navShop: "The shop floor", navDepartments: "Departments", navHome: "The counter",
    heroLine1: "Steel for the road.", heroLine2: "Relics for what lies beyond.",
    enterArmory: "Enter the armory", seeTheWares: "See what is on the floor",
    guildLine: "Ironmark Guild · Third Seal", estLine: "Keeping counter since the Age of Ash", placeLine: "Low Quarter of Vael, Kingdom of Aster",
    merchantWord: [
      { title: "Weighed and marked", text: "Every piece on the floor carries a maker's mark and the guild seal that sanctioned it." },
      { title: "Struck, not stamped", text: "Nothing here left a mould. The benches at Ironmark and Ashfell work by hand." },
      { title: "The ledger is kept", text: "Prices, stock and provenance are written down. Ask to see the book." },
    ],
    departmentsEyebrow: "Five doors off the counter", departmentsHead: "Departments of the house",
    departmentsNote: "The shop is arranged as the guild requires: edged work apart from plate, and the alchemist's shelf behind the counter.",
    floorHead: "On the floor this season", viewArtifact: "View the record",
    noticeHead: "A notice, nailed to the post",
    noticeText: "This shop is a portfolio demonstration. Nothing you add to the satchel is ordered, no account is made, no payment can be taken, and every price, kingdom, maker and guild seal here is invented.",
    noticeSigned: "— kept by the house, in the merchant's own hand",
    shopEyebrow: "The shop floor", askTheMerchant: "Ask the merchant", searchPlaceholder: "A sword, mithril, something cold...",
    allWares: "Everything on the floor", wares: "pieces on the floor",
    noneFound: "Nothing of that description", noneFoundSub: "Ask again, or try another door off the counter.",
    backToFloor: "Back to the floor",
    forgedBy: "Forged by", merchantsNote: "The merchant's note", merchantsPrice: "The merchant's price",
    addToSatchel: "Add to the satchel", watch: "Set on the watchlist", watching: "On the watchlist",
    sameShelf: "Also on this shelf",
    recMaterial: "Material", recOrigin: "Origin", recEra: "Era", recWeight: "Weight", recStock: "In the back",
    stockLine: "in the back room this week",
    demoLine: "Demonstration shop: the satchel is kept in your browser alone and cannot place an order.",
    footerText: "An invented armorer's shop, built as a safe portfolio demonstration over a real storefront's catalogue.",
    footerShop: "The shop", footerHouse: "The house",
    footerHouseText: "Medivi keeps counter in the Low Quarter of Vael under the third seal of the Ironmark Guild. The kingdom, the guild and the makers are fiction.",
    cartTitle: "Bill of lading", cartSub: "Set aside, not yet sealed",
    manifestHead: "Manifest of goods", entryNo: "Entry",
    colWare: "Ware", colCount: "Count", colEach: "Each", colSum: "Sum",
    colDept: "Department", colStock: "On hand", colState: "State",
    strikeOut: "Strike out", emptyCart: "Nothing set aside yet.",
    sumOfWares: "Sum of wares", carriage: "Carriage", dueAtCounter: "Due at the counter",
    manifestNote: "Weights are the house's own. Anything that leaves the counter is checked twice against this sheet.",
    toTheLedger: "To the ledger", keepLooking: "Keep looking",
    checkoutTitle: "The ledger", checkoutSub: "Written in the merchant's hand and kept in the house book. Nothing here leaves the page.",
    backToManifest: "Back to the manifest", backToLedger: "Back to the ledger",
    handOfBearer: "Hand of the bearer", mannerOfCarriage: "Manner of carriage", toTheSeal: "To the seal",
    fBearer: "Name of bearer", fBearerP: "Aldric of Hollowfen",
    fRoad: "Road and house", fRoadP: "Third house past the tanner",
    fTown: "Town", fTownP: "Vael",
    fKingdom: "Kingdom", fKingdomP: "Aster",
    fMark: "Guild mark (if held)", fMarkP: "Optional",
    carriageRider: "Rider", carriageRiderEta: "Three days, one horse, no stops",
    carriageCaravan: "Caravan", carriageCaravanEta: "Nine days, guarded, goes by the pass",
    carriageRaven: "Raven and courier", carriageRavenEta: "Same night, light goods only",
    byTheHouse: "By the house",
    paymentTitle: "The seal", paymentSub: "Choose how the debt is settled. The merchant presses the wax; the guild keeps the impression.",
    payCoin: "Coin at the counter", payCoinNote: "Counted and weighed before the goods leave.",
    payCredit: "Letter of credit", payCreditNote: "Drawn on a house the guild recognises.",
    payAccount: "Guild account", payAccountNote: "Settled at the turn of the season against your seal.",
    pressTheSeal: "Press the seal", sealNote: "No coin changes hands. This is a demonstration.",
    sealedTitle: "Sealed", sealedSub: "The entry is written and the wax is set. The house keeps one copy, the bearer the other.",
    sealedNote: "Nothing was charged and nothing will be sent.",
    watchTitle: "Watch ledger", watchSub: "Pieces you asked the merchant to hold an eye on.",
    emptyWatch: "No pieces watched yet.", stopWatching: "Stop watching",
    adminTitle: "Counting house", adminSub: "What the merchant sees: stock on hand, what is low, and what is already spoken for.",
    statWares: "Wares on the floor", statStock: "Pieces on hand", statLow: "Running low", statValue: "Floor value",
    stateOnFloor: "On the floor", stateLow: "Low", stateSpoken: "Spoken for",
  },
  pt: {
    banner: "Uma demonstração de portfólio. Nenhuma moeda troca de mãos, nenhum pedido é enviado.",
    house: "Armeiro & Provedor",
    navShop: "O salão", navDepartments: "Departamentos", navHome: "O balcão",
    heroLine1: "Aço para a estrada.", heroLine2: "Relíquias para o que vem depois.",
    enterArmory: "Entrar no arsenal", seeTheWares: "Ver o que está no salão",
    guildLine: "Guilda de Ironmark · Terceiro Selo", estLine: "No balcão desde a Era das Cinzas", placeLine: "Bairro Baixo de Vael, Reino de Aster",
    merchantWord: [
      { title: "Pesado e marcado", text: "Cada peça do salão traz a marca do artesão e o selo da guilda que a sancionou." },
      { title: "Forjado, não moldado", text: "Nada aqui saiu de um molde. As bancadas de Ironmark e Ashfell trabalham à mão." },
      { title: "O livro é mantido", text: "Preços, estoque e procedência ficam escritos. Peça para ver o livro." },
    ],
    departmentsEyebrow: "Cinco portas a partir do balcão", departmentsHead: "Departamentos da casa",
    departmentsNote: "A loja segue o que a guilda exige: trabalho de fio separado das armaduras, e a prateleira do alquimista atrás do balcão.",
    floorHead: "No salão nesta estação", viewArtifact: "Ver o registro",
    noticeHead: "Um aviso, pregado no poste",
    noticeText: "Esta loja é uma demonstração de portfólio. Nada que você colocar na bolsa é encomendado, nenhuma conta é criada, nenhum pagamento pode ser feito, e todo preço, reino, artesão e selo de guilda aqui é inventado.",
    noticeSigned: "— mantido pela casa, pela própria mão do mercador",
    shopEyebrow: "O salão", askTheMerchant: "Pergunte ao mercador", searchPlaceholder: "Uma espada, mithril, algo frio...",
    allWares: "Tudo no salão", wares: "peças no salão",
    noneFound: "Nada com essa descrição", noneFoundSub: "Pergunte de novo, ou tente outra porta do balcão.",
    backToFloor: "Voltar ao salão",
    forgedBy: "Forjado por", merchantsNote: "Nota do mercador", merchantsPrice: "Preço do mercador",
    addToSatchel: "Colocar na bolsa", watch: "Anotar na lista", watching: "Na lista",
    sameShelf: "Também nesta prateleira",
    recMaterial: "Material", recOrigin: "Origem", recEra: "Era", recWeight: "Peso", recStock: "Nos fundos",
    stockLine: "nos fundos esta semana",
    demoLine: "Loja de demonstração: a bolsa fica apenas no seu navegador e não gera pedido.",
    footerText: "Uma loja de armeiro inventada, feita como demonstração segura de portfólio sobre o catálogo de uma loja real.",
    footerShop: "A loja", footerHouse: "A casa",
    footerHouseText: "A Medivi mantém balcão no Bairro Baixo de Vael sob o terceiro selo da Guilda de Ironmark. O reino, a guilda e os artesãos são ficção.",
    cartTitle: "Carta de carga", cartSub: "Separado, ainda sem selo",
    manifestHead: "Manifesto de mercadorias", entryNo: "Registro",
    colWare: "Peça", colCount: "Qtd.", colEach: "Unidade", colSum: "Soma",
    colDept: "Departamento", colStock: "Em estoque", colState: "Estado",
    strikeOut: "Riscar", emptyCart: "Nada separado ainda.",
    sumOfWares: "Soma das peças", carriage: "Transporte", dueAtCounter: "Devido no balcão",
    manifestNote: "Os pesos são os da casa. Tudo que sai do balcão é conferido duas vezes contra esta folha.",
    toTheLedger: "Ir ao registro", keepLooking: "Continuar olhando",
    checkoutTitle: "O registro", checkoutSub: "Escrito pela mão do mercador e guardado no livro da casa. Nada daqui sai da página.",
    backToManifest: "Voltar ao manifesto", backToLedger: "Voltar ao registro",
    handOfBearer: "Mão do portador", mannerOfCarriage: "Modo de transporte", toTheSeal: "Ir ao selo",
    fBearer: "Nome do portador", fBearerP: "Aldric de Hollowfen",
    fRoad: "Rua e casa", fRoadP: "Terceira casa depois do curtidor",
    fTown: "Vila", fTownP: "Vael",
    fKingdom: "Reino", fKingdomP: "Aster",
    fMark: "Marca de guilda (se tiver)", fMarkP: "Opcional",
    carriageRider: "Cavaleiro", carriageRiderEta: "Três dias, um cavalo, sem paradas",
    carriageCaravan: "Caravana", carriageCaravanEta: "Nove dias, escoltada, pela passagem",
    carriageRaven: "Corvo e mensageiro", carriageRavenEta: "Na mesma noite, só carga leve",
    byTheHouse: "Por conta da casa",
    paymentTitle: "O selo", paymentSub: "Escolha como a dívida é quitada. O mercador prensa a cera; a guilda guarda a impressão.",
    payCoin: "Moeda no balcão", payCoinNote: "Contada e pesada antes de a mercadoria sair.",
    payCredit: "Carta de crédito", payCreditNote: "Sacada sobre uma casa que a guilda reconhece.",
    payAccount: "Conta na guilda", payAccountNote: "Quitada na virada da estação contra o seu selo.",
    pressTheSeal: "Prensar o selo", sealNote: "Nenhuma moeda troca de mãos. Isto é uma demonstração.",
    sealedTitle: "Selado", sealedSub: "O registro está escrito e a cera está posta. A casa fica com uma via, o portador com a outra.",
    sealedNote: "Nada foi cobrado e nada será enviado.",
    watchTitle: "Livro de vigia", watchSub: "Peças que você pediu ao mercador para manter de olho.",
    emptyWatch: "Nenhuma peça em vigia ainda.", stopWatching: "Parar de vigiar",
    adminTitle: "Casa de contas", adminSub: "O que o mercador vê: estoque em mãos, o que está baixo e o que já está reservado.",
    statWares: "Peças no salão", statStock: "Unidades em mãos", statLow: "Estoque baixo", statValue: "Valor do salão",
    stateOnFloor: "No salão", stateLow: "Baixo", stateSpoken: "Reservado",
  },
};


