"use client";
import Link from "next/link";
import { findVariant } from "@/lib/catalog";
import { localizedGood } from "@/lib/armory";
import { useDemo } from "./demo-provider";
import { useArmory, Mark, PageHead, Parchment, ProductFrame } from "./armory-primitives";
export function CartView() {
  const { a, locale, tr, formatMoney } = useArmory();
  const { state, updateQuantity, totalCents } = useDemo();
  const lines = state.cart.flatMap(item=>{const match=findVariant(item.variantId);return match?[{item,match}]:[]});
  return <div className="arm-wrap max-w-[1068px] py-[52px]"><PageHead title={a("cartTitle")} sub={a("cartSub")}/>
    {!lines.length ? <div className="arm-plate py-20 text-center"><Mark name="scroll" size={40} className="mx-auto opacity-50"/><p className="arm-ui mt-5 text-[21px]">{a("emptyCart")}</p><Link className="arm-button mt-7" href="/catalog">{a("seeTheWares")}</Link></div> : <>
      <Parchment className="p-6 sm:p-10"><div className="arm-ui flex flex-wrap items-center justify-between gap-4 border-b-2 border-[#3a2c186b] pb-5"><h2 className="arm-display flex items-center gap-3 text-[30px]"><Mark name="scroll" tone="ink" size={26}/>{a("manifestHead")}</h2><span className="text-[13px] uppercase tracking-widest text-[#6a5638]">{a("entryNo")} MMXCI–1147</span></div>
      <div className="arm-ui mt-5 hidden grid-cols-[70px_minmax(0,1fr)_92px_92px_118px] gap-4 text-[12px] uppercase tracking-widest text-[#6a5638] min-[900px]:grid"><span/><span>{a("colWare")}</span><span>{a("colCount")}</span><span className="text-right">{a("colEach")}</span><span className="text-right">{a("colSum")}</span></div>
      <div>{lines.map(({item,match})=><div key={item.variantId} className="arm-ui grid gap-4 border-b border-[#3a2c1845] py-5 min-[900px]:grid-cols-[70px_minmax(0,1fr)_92px_92px_118px] min-[900px]:items-center"><Link href={`/product/${match.product.slug}`}><ProductFrame src={match.product.image} alt={tr(match.product.name)} className="h-[70px] w-[70px] border border-[#2a1f1480]"/></Link><div><Link href={`/product/${match.product.slug}`} className="text-[21px]">{tr(match.product.name)}</Link><p className="text-[13px] text-[#5c4a30]">{tr(match.product.material)}{localizedGood(locale,match.product.slug)?.origin ? ` · ${localizedGood(locale,match.product.slug)?.origin}` : ""}{match.product.variants.length>1 ? ` · ${tr(match.variant.name)}` : ""}</p><button className="mt-2 text-[13px] uppercase underline text-[#7a3034]" onClick={()=>updateQuantity(item.variantId,0)}>{a("strikeOut")}</button></div><div className="flex w-fit items-center border border-[#2a1f1466]"><button className="min-h-11 min-w-8" onClick={()=>updateQuantity(item.variantId,Math.max(1,item.quantity-1))} aria-label={tr("Decrease quantity")}>−</button><span className="min-w-7 text-center">{item.quantity}</span><button className="min-h-11 min-w-8" disabled={item.quantity>=match.variant.stock} onClick={()=>updateQuantity(item.variantId,item.quantity+1)} aria-label={tr("Increase quantity")}>+</button></div><span className="text-[16px] min-[900px]:text-right">{formatMoney(match.variant.priceCents??match.product.priceCents)}</span><strong className="text-[19px] min-[900px]:text-right">{formatMoney((match.variant.priceCents??match.product.priceCents)*item.quantity)}</strong></div>)}</div>
      <div className="arm-ui ml-auto mt-8 max-w-[340px] space-y-3"><div className="flex justify-between"><span>{a("sumOfWares")}</span><span>{formatMoney(totalCents)}</span></div><div className="flex justify-between"><span>{a("carriage")}</span><span>{a("byTheHouse")}</span></div><div className="border-t border-[#3a2c1866] pt-3 flex items-end justify-between"><span className="text-[12px] uppercase tracking-widest">{a("dueAtCounter")}</span><strong className="text-[30px]">{formatMoney(totalCents)}</strong></div></div><p className="mt-7 max-w-[56ch] text-[14px] italic leading-6 text-[#5c4a30]">{a("manifestNote")}</p></Parchment>
      <div className="mt-8 flex flex-wrap items-center gap-6"><Link href="/checkout" className="arm-button">{a("toTheLedger")} →</Link><Link href="/catalog" className="arm-link">← {a("keepLooking")}</Link></div>
    </>}</div>;
}
